name: target-discovery
channels:
  - defaults
dependencies:
  - python=3.10.21
  - pip
  - pip:
      - pandas==2.3.3
      - numpy==2.2.6
      - scipy==1.15.3
      - matplotlib==3.10.9
      - seaborn==0.13.2
      - lifelines==0.30.0
      - jupyter==1.1.1
      - nbconvert==7.17.1
      - ipykernel==7.3.0
